#!/usr/bin/env python3
"""Distill a per-version GameParams.data into a small Python module.

Usage:
    python3 tools/distill_gameparams.py \\
        --gameparams /path/to/GameParams.data \\
        --schema    tools/distill_schema.yaml \\
        --output    replay_unpack/clients/wows/versions/<ver>/game_params.py
"""
import argparse
import os
import sys
from collections import defaultdict

import yaml

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _gameparams_unpickle import load_gameparams, _GPItem


def _to_serializable(value):
    """Convert _GPItem instances to plain dicts so pprint can render them.

    Preserves the nested shape (a `typeinfo` field stays a sub-dict on the
    record - it is NOT merged into the parent). Non-scalar attributes inside
    the _GPItem are dropped: extracting deeply nested data is the job of the
    deferred dot-notation feature, not this conversion.
    """
    if isinstance(value, _GPItem):
        return {k: v for k, v in value.__dict__.items()
                if isinstance(v, (str, int, float, bool, type(None)))}
    return value


def pick_rule(schema, type_, species):
    specific = '%s/%s' % (type_, species) if species else None
    if specific and specific in schema:
        return schema[specific]
    return schema.get(type_)


def apply_rule(entry, rule, missing_log):
    out = {}
    for field in rule['fields']:
        if '.' in field:
            raise ValueError(
                'dotted paths are not yet supported (got %r); '
                'use only top-level attribute names' % field)
        if not hasattr(entry, field):
            missing_log.add(field)
            out[field] = None
        else:
            out[field] = _to_serializable(getattr(entry, field))
    return out


def render_module(by_id):
    lines = [
        '# coding=utf-8',
        '# Auto-generated by tools/distill_gameparams.py - do not edit.',
        '',
        'SCHEMA_VERSION = 1',
        '',
        'BY_ID = {',
    ]
    for gp_id in sorted(by_id):
        lines.append('    %d: %r,' % (gp_id, by_id[gp_id]))
    lines.append('}')
    lines.append('')
    lines.append('BY_INDEX = {v[\'index\']: v for v in BY_ID.values()}')
    lines.append('')
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--gameparams', required=True)
    parser.add_argument('--schema', required=True)
    parser.add_argument('--output', required=True)
    parser.add_argument('--region', default='')
    args = parser.parse_args()

    with open(args.schema) as f:
        schema = yaml.safe_load(f)

    raw = load_gameparams(args.gameparams)
    if args.region not in raw:
        print('error: region %r not in GameParams (have %r)' %
              (args.region, sorted(raw)), file=sys.stderr)
        sys.exit(1)
    region = raw[args.region]

    by_id = {}
    errors = []
    skipped_no_rule = 0
    missing_per_type = defaultdict(set)
    counts = defaultdict(int)

    for index, entry in region.items():
        # The dict-key is the canonical identifier in this dataset (e.g.
        # "PFSD010_Cassard"). The entry's own .index attribute holds only the
        # type prefix (e.g. "PFSD010"). Override so the schema's `index` field
        # picks up the canonical name.
        entry.__dict__['index'] = index
        try:
            ti = getattr(entry, 'typeinfo', None)
            type_ = getattr(ti, 'type', None) if ti is not None else None
            species = getattr(ti, 'species', None) if ti is not None else None
            rule = pick_rule(schema, type_, species)
            if rule is None:
                skipped_no_rule += 1
                continue
            record = apply_rule(entry, rule, missing_per_type[(type_, species)])
            gp_id = record.get('id')
            if not isinstance(gp_id, int):
                errors.append((index, 'no integer id'))
                continue
            if gp_id in by_id:
                errors.append((index, 'id collision with %r' % by_id[gp_id].get('index')))
                continue
            by_id[gp_id] = record
            counts[(type_, species)] += 1
        except Exception as e:
            errors.append((index, repr(e)))

    if not by_id:
        print('error: zero records emitted', file=sys.stderr)
        for idx, msg in errors[:20]:
            print('  %s: %s' % (idx, msg), file=sys.stderr)
        sys.exit(2)

    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    with open(args.output, 'w', encoding='utf-8') as f:
        f.write(render_module(by_id))

    print('wrote %d records to %s' % (len(by_id), args.output), file=sys.stderr)
    for (t, s), n in sorted(counts.items()):
        label = '%s/%s' % (t, s) if s else str(t)
        print('  %s: %d' % (label, n), file=sys.stderr)
    print('skipped (no matching rule): %d' % skipped_no_rule, file=sys.stderr)
    for (t, s), missing in missing_per_type.items():
        if missing:
            label = '%s/%s' % (t, s) if s else str(t)
            print('  warn: %s missing fields: %s' % (label, sorted(missing)), file=sys.stderr)
    if errors:
        print('errors: %d' % len(errors), file=sys.stderr)
        for idx, msg in errors[:10]:
            print('  %s: %s' % (idx, msg), file=sys.stderr)


if __name__ == '__main__':
    main()
